name:         ztar
version:      1.0.2
license:      BSD3
author:       Brandon Chinn <brandonchinn178@gmail.com>
maintainer:   Brandon Chinn <brandonchinn178@gmail.com>
category:     Codec
synopsis:     Creating and extracting arbitrary archives
description:  Creating and extracting arbitrary archives.
extra-doc-files:
  - CHANGELOG.md
  - README.md

github: brandonchinn178/ztar

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - bytestring >= 0.10.8
    - directory >= 1.3
    - filepath >= 1.4.1
    - path >= 0.5
    # - tar >= 0.5
    - zip >= 1.0
    - zlib >= 0.6
    # For Codec.Archive.Tar
    - deepseq
    - process
    - text
    - unix-compat

tests:
  example:
    main: test/Example.hs
    dependencies:
      - base
      - path
      - path-io
      - ztar

  ztar-test:
    main: test/Test.hs
    dependencies:
      - base
      - bytestring
      - filepath
      - path
      - path-io
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-quickcheck
      - ztar
