name:         ztar
version:      1.0.2
license:      BSD3
author:       Brandon Chinn <brandonchinn178@gmail.com>
maintainer:   Brandon Chinn <brandonchinn178@gmail.com>
category:     Codec
synopsis:     Creating and extracting arbitrary archives
description:  Creating and extracting arbitrary archives.
extra-doc-files:
  - CHANGELOG.md
  - README.md

github: brandonchinn178/ztar

flags:
  dev:
    description:  Turn on development settings.
    manual:       true
    default:      false

ghc-options: -Wall
when:
  - condition: flag(dev)
    ghc-options: -Werror
  - condition: impl(ghc >= 8.0)
    ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wnoncanonical-monad-instances
  - condition: impl(ghc <= 8.6)
    ghc-options:
      - -Wnoncanonical-monadfail-instances

library:
  source-dirs: src
  dependencies:
    base: '>= 4.7 && < 5'
    bytestring: '>= 0.10.8 && < 0.11'
    directory: '>= 1.3 && < 1.4'
    filepath: '>= 1.4.1 && < 1.5'
    path: '>= 0.5 && < 0.8'
    # tar: '>= 0.5 && < 0.6'
    zip: '>= 1.0 && < 1.4'
    zlib: '>= 0.6 && < 0.7'
    # For Codec.Archive.Tar
    deepseq:
    process:
    text:
    unix-compat:

_test_aliases:
  - &test-files
    source-dirs: test
    other-modules: []

tests:
  example:
    main: Example.hs
    <<: *test-files
    dependencies:
      base:
      path:
      path-io:
      ztar:

  ztar-test:
    main: Test.hs
    <<: *test-files
    dependencies:
      base:
      bytestring:
      filepath:
      path:
      path-io:
      QuickCheck:
      quickcheck-instances:
      tasty:
      tasty-quickcheck:
      ztar:
