name:         ztar
version:      0.1.3
license:      BSD3
author:       Brandon Chinn <brandonchinn178@gmail.com>
maintainer:   Brandon Chinn <brandonchinn178@gmail.com>
category:     Codec
synopsis:     Creating and extracting arbitrary archives
description:  Creating and extracting arbitrary archives.
extra-doc-files:
  - CHANGELOG.md
  - README.md

github: brandonchinn178/ztar

flags:
  dev:
    description:  Turn on development settings.
    manual:       true
    default:      false
  typed-paths:
    description:  Use the Path library.
    manual:       true
    default:      false

ghc-options: -Wall
when:
  - condition: flag(dev)
    ghc-options: -Werror
  - condition: impl(ghc >= 8.0)
    ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wnoncanonical-monad-instances
      - -Wnoncanonical-monadfail-instances
  - condition: flag(typed-paths)
    cpp-options: -DTYPED_PATHS

library:
  source-dirs: src
  dependencies:
    base: '>= 4.7 && < 5'
    bytestring: '>= 0.10.8 && < 0.11'
    directory: '>= 1.3 && < 1.4'
    filepath: '>= 1.4.1 && < 1.5'
    # tar: '>= 0.5 && < 0.6'
    zip: '>= 0.2 && < 0.3'
    zlib: '>= 0.6 && < 0.7'
    # For zip-0.2.0
    path:
    # For Codec.Archive.Tar
    deepseq:
    process:
    text:
    unix-compat:
  when:
    - condition: flag(typed-paths)
      dependencies:
        path: '>= 0.5 && < 0.7'

_test_aliases:
  - &test-files
    source-dirs: test
    other-modules:
      - Utilities

tests:
  example:
    main: Example.hs
    <<: *test-files
    dependencies:
      base:
      path:
      path-io:
      ztar:

  ztar-test:
    main: Test.hs
    <<: *test-files
    dependencies:
      base:
      bytestring:
      bytestring-arbitrary:
      extra:
      path:
      path-io:
      QuickCheck:
      tasty:
      tasty-quickcheck:
      ztar:
